package de.dhbw.nerdlegame.message;

public enum MessageType {
    GAME_STATE_CHANGED,
    GAME_STARTS,
    GUESS_RESULT,
    PLAYER_WINS,
    TOO_LITTLE_TIME_SINCE_LAST_GUESS_ERROR,
    GUESSING_NOT_STARTED_YET,
    NO_MORE_GUESSES_AVAILABLE,
    PLAYER_GUESS
}
